<?php
declare(strict_types=1);

/** @var $viewModel \Zaproo\TestWork\ViewModel\CustomerStatus */
/** @var $block \Magento\Framework\View\Element\Template */

$viewModel = $block->getViewModel();

?>

Current Status: <?= $block->escapeHtml($viewModel->getStatus()); ?>
<form class="form" action="<?= $viewModel->getFormAction() ?>" method="post">
    <input class="input-text" name="status" type="text">
    <input class="action save primary" type="submit">
</form>
